name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: './backend/package-lock.json'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: 5000
          envkey_TEST_MONGODB_URI: mongodb+srv://admin:admin@cluster0.53hsnfw.mongodb.net/testUser?retryWrites=true&w=majority
          directory: ../../backend
          file_name: .env
          fail_on_empty: false
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test